// React 页面模块组装(自 markdownToReact.ts 拆分):把渲染后的 HTML、script
// 块与页面元数据拼成一份 TSX 页面模块源码(文本;由 plugin.ts 内 oxc 以
// automatic JSX runtime 编译成可执行 JS)。

import { extractComponentNames, serializeHtmlToJsx } from './serializeHtmlToJsx'
import type { PlaceholderStore } from './placeholders'
import type { MarkdownEnv, PageData } from '../shared'

/** __pageData 顶层导出(契约与上游一致:主题 useData() 读取) */
function injectPageDataCode(data: PageData): string {
  return `export const __pageData = JSON.parse(${JSON.stringify(
    JSON.stringify(data)
  )})`
}

/**
 * 合并多个 script 块时去重 import 语句:多个块可能各自写同一句 import,
 * 提升到模块顶层后会重复声明。逐行处理(单行 import 语义),同句只留首条。
 */
function dedupeImports(blocks: string[]): string {
  const seen = new Set<string>()
  const out: string[] = []
  for (const block of blocks) {
    for (const line of block.split('\n')) {
      if (/^\s*import\s/.test(line)) {
        const key = line.replace(/\s+/g, ' ').trim()
        if (seen.has(key)) continue
        seen.add(key)
        out.push(line)
      } else {
        out.push(line)
      }
    }
  }
  return out.join('\n')
}

/** 注释掉用户 script 里的 `export default`(页面 default 组件由本模块生成) */
function stripExportDefault(code: string): string {
  const lines = code.split('\n')
  const out: string[] = []
  let i = 0
  const countBrackets = (s: string) =>
    [...s].reduce((acc, c) => acc + (c === '{' ? 1 : c === '}' ? -1 : 0), 0)

  while (i < lines.length) {
    const line = lines[i]
    if (/^\s*export\s+default\b/.test(line)) {
      let depth = countBrackets(line)
      if (depth <= 0 && !/;\s*$/.test(line) && !/\}\s*$/.test(line)) {
        // 简单值形式(export default foo)
        out.push('// removed: user export-default (页面组件由本模块生成)')
        i++
        continue
      }
      // 跨行对象/表达式:收集到花括号平衡
      let buf = line
      i++
      while (i < lines.length && depth > 0) {
        buf += '\n' + lines[i]
        depth += countBrackets(lines[i])
        i++
      }
      const commented = buf
        .split('\n')
        .map((l) => (l ? `// ${l}` : '//'))
        .join('\n')
      out.push('// removed: user export-default (页面组件由本模块生成)')
      out.push(commented)
      continue
    }
    out.push(line)
    i++
  }
  return out.join('\n')
}

/** <script client>(MPA client JS):内容以注释保留,避免静默丢弃 */
const scriptClientRE = /<script\b[^>]*client\b[^>]*>/i

/**
 * 把 script 顶层代码按行分拣:
 * - import 语句 → 模块顶层(imports)
 * - export * 语句(含跨行的 function/const)→ 模块顶层(restModule)
 * - 其余语句/声明 → Page() 组件体内(pageCode,可合法使用 hooks)
 * 用花括号深度判断跨行语句边界;单行无括号的语句各自成行。
 */
function splitTopLevel(code: string): {
  imports: string[]
  restModule: string[]
  body: string[]
} {
  const lines = code.split('\n')
  const imports: string[] = []
  const restModule: string[] = []
  const body: string[] = []
  let bucket: 'import' | 'module' | 'body' | null = null
  let depth = 0
  const braces = (s: string) => {
    let d = 0
    for (const c of s) {
      if (c === '{') d++
      else if (c === '}') d--
    }
    return d
  }
  for (const line of lines) {
    if (bucket === null) {
      const t = line.trim()
      if (!t) {
        body.push(line)
        continue
      }
      if (/^import\s/.test(t)) bucket = 'import'
      else if (/^export\b/.test(t)) bucket = 'module'
      else bucket = 'body'
    }
    const target =
      bucket === 'import' ? imports : bucket === 'module' ? restModule : body
    target.push(line)
    depth += braces(line)
    if (depth <= 0) bucket = null
  }
  return { imports, restModule, body }
}

/** <style> 块是否声明 scoped(plugin-sfc 不解析属性,直接看开标签文本) */
function isScopedStyleBlock(block: { tagOpen: string }): boolean {
  return /^<style\b[^>]*\bscoped\b/i.test(block.tagOpen)
}

/** 读取 <style> 块的 lang 属性;无则 undefined(按 css 处理) */
function styleBlockLang(tagOpen: string): string | undefined {
  const m = tagOpen.match(
    /\blang\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+))/i
  )
  return m ? (m[1] ?? m[2] ?? m[3]) : undefined
}

/**
 * 组装 React 页面模块(TSX 文本;由 plugin.ts 内 oxc automatic JSX 编译):
 *
 *   // generated by vitepress-react
 *   // ---- <script> imports / named exports (module top; shared scope) ----
 *   <import 语句(去重)>
 *   <export function/const … 等具名导出,模块顶层>
 *   export const __pageData = JSON.parse(…)
 *   [<style> 块:客户端运行时注入 style 标签(SSR 不注入)]
 *   export default function Page() {
 *     // ---- <script> page scope (component body) ----
 *     <script 里其余语句:可含 useState 等 hooks,与正文 JSX(<>{expr}</> 等)共享作用域>
 *     return ( <div className="vp-doc">…JSX…</div> )
 *   }
 *
 * 正文动态能力契约(V2):正文裸 `{…}`
 * 一律字面文本;动态内容由作者**显式写成 JSX**(`<>{expr}</>` Fragment /
 * 组件标签 / ::: react),由 markdown/jsxTokenRules 的 token 级规则在 md 内
 * 占位(env.jsxStore → @@VP_HTML / data-vp-jsx),序列化时原样恢复 —— 与
 * Page 函数体共享作用域(可响应 hooks 更新)。
 * 需要完整交互时仍用 <script> 定义的组件标签。
 *
 * 样式(themeConfig.markdownScopedCss 开启时,见 plugin.ts 的 jsx-scoped 管线):
 *  - <style scoped> 块:嵌入 vp-doc 根的 `<style scoped>{StringLiteral}</style>`,
 *    由 jsx-scoped transform 提取为虚拟 css 模块(追加 [data-v-{hash}] 选择器);
 *  - 其余 <style> 块:维持运行时全局注入;关闭开关时全部样式均走全局注入。
 */
export function createReactPageSrc(
  html: string,
  sfcBlocks: MarkdownEnv['sfcBlocks'],
  pageData: PageData,
  expressions: PlaceholderStore,
  scopedCssEnabled = false
): string {
  const parts: string[] = []
  parts.push(`// generated by vitepress-react (md → React page module)`)

  const scripts = sfcBlocks?.scripts?.length
    ? sfcBlocks.scripts
    : sfcBlocks?.scriptSetup
      ? [sfcBlocks.scriptSetup]
      : []

  const moduleImports: string[] = []
  const moduleRest: string[] = []
  const pageCode: string[] = []
  for (const block of scripts) {
    if (scriptClientRE.test(block.tagOpen)) {
      parts.push(`// <script client> (MPA client JS)`)
      parts.push(
        block.contentStripped
          .split('\n')
          .map((l) => `//   ${l}`)
          .join('\n')
      )
      continue
    }
    const { imports, restModule, body } = splitTopLevel(
      stripExportDefault(block.contentStripped)
    )
    moduleImports.push(...imports)
    moduleRest.push(...restModule)
    pageCode.push(...body)
  }

  // 组件引用解析名:imports/具名导出(模块顶层)+ Page 作用域局部声明
  const componentNames = new Set<string>()
  for (const n of extractComponentNames(
    [...moduleImports, ...moduleRest, ...pageCode].join('\n')
  )) {
    componentNames.add(n)
  }

  // Vue 默认主题全局注册的 markdown 可用标签(Badge 等)→ 编译期自动从主题导入。
  // 只在最终 HTML 里出现才算被使用(代码块内容已被 markdown-it 转义,不会误中)。
  const THEME_MD_TAGS: Record<string, string> = {
    Badge: 'VPBadge',
    VPBadge: 'VPBadge'
  }
  {
    const tagRe = new RegExp(
      `<(${Object.keys(THEME_MD_TAGS).join('|')})(?=[\\s/>])`,
      'g'
    )
    const used = new Set<string>()
    let m: RegExpExecArray | null
    while ((m = tagRe.exec(html))) {
      used.add(m[1])
    }
    // 额外扫描被整行占位的 JSX HTML,确保 <Badge/> 之类自动导入主题组件
    const innerRe = new RegExp(
      `<(${Object.keys(THEME_MD_TAGS).join('|')})(?=[\\s/>])`,
      'g'
    )
    for (const e of expressions) {
      if (e.html == null) continue
      innerRe.lastIndex = 0
      let im: RegExpExecArray | null
      while ((im = innerRe.exec(e.html))) used.add(im[1])
    }
    if (used.size) {
      moduleImports.push(`// theme components used by markdown`)
      for (const local of used) {
        const exportName = THEME_MD_TAGS[local] ?? local
        moduleImports.push(
          exportName === local
            ? `import { ${exportName} } from '@10coding/vitepress-react/theme'`
            : `import { ${exportName} as ${local} } from '@10coding/vitepress-react/theme'`
        )
        componentNames.add(local)
      }
    }
  }

  if (moduleImports.length || moduleRest.length) {
    parts.push(
      `// ---- <script> imports / named exports (module top; shared scope) ----`
    )
    if (moduleImports.length) {
      parts.push(dedupeImports([moduleImports.join('\n')]))
    }
    if (moduleRest.length) parts.push(moduleRest.join('\n'))
  }
  parts.push(injectPageDataCode(pageData))

  // <style> 块:scoped 开关开启时,<style scoped> 嵌入 Page JSX(由 plugin.ts 的
  // jsx-scoped transform 提取为虚拟 css 模块);其余维持运行时注入全局 style。
  const styles = sfcBlocks?.styles ?? []
  const scopedStyles = scopedCssEnabled ? styles.filter(isScopedStyleBlock) : []
  const globalStyles = scopedCssEnabled
    ? styles.filter((s) => !isScopedStyleBlock(s))
    : styles

  // 运行时注入 style 标签(全局样式;SSR 阶段不注入)
  if (globalStyles.length) {
    const css = globalStyles.map((s) => s.contentStripped).join('\n')
    parts.push(`const __vpStyles__ = ${JSON.stringify(css)}`)
    parts.push(
      `if (typeof document !== 'undefined') { const __el__ = document.createElement('style'); __el__.textContent = __vpStyles__; document.head.appendChild(__el__) }`
    )
  }
  if (sfcBlocks?.customBlocks?.length) {
    parts.push(
      `// NOTE: ${sfcBlocks.customBlocks.length} 个 custom block 未输出(React 暂无对应机制)`
    )
  }

  // 正文 → JSX(组件标签解析为标识符引用;@@VP_HTML_n@@ 占位还原为作者 JSX)
  const exprMap: Record<string, { html?: string }> = {}
  expressions.forEach((e, i) => {
    if (e.html != null) exprMap[`${i}`] = { html: e.html }
  })
  const body = serializeHtmlToJsx(html, componentNames, exprMap)
  if (body.warnings.length) {
    parts.push(`// NOTE (markdownToReact):`)
    for (const w of body.warnings) parts.push(`//   - ${w}`)
  }

  let contentJsx = body.code
  if (scopedStyles.length) {
    // 把 <style scoped> 以 StringLiteral 子节点嵌入 vp-doc 根:jsx-scoped 的
    // transform 会提取内容并替换为虚拟 css import(页面级 [data-v-{hash}] 样式),
    // 提取器按任意 JSX 元素移除,渲染树里不会残留 <style> 标签。
    const styleNodes = scopedStyles
      .map((s) => {
        const lang = styleBlockLang(s.tagOpen)
        const langAttr = lang ? ` lang="${lang}"` : ''
        return `<style scoped${langAttr}>{${JSON.stringify(s.contentStripped)}}</style>`
      })
      .join('\n')
    const rootOpen = '<div className="vp-doc">'
    const at = contentJsx.indexOf(rootOpen)
    if (at !== -1) {
      contentJsx =
        contentJsx.slice(0, at + rootOpen.length) +
        `\n${styleNodes}` +
        contentJsx.slice(at + rootOpen.length)
    } else {
      parts.push(`// NOTE: <style scoped> 未嵌入 vp-doc 根,scoped 样式未生效`)
    }
  }

  parts.push(`export default function Page() {`)
  if (pageCode.length) {
    parts.push(`  // ---- <script> page scope (component body) ----`)
    for (const l of pageCode) parts.push(`  ${l}`)
  }
  parts.push(`  return (`)
  parts.push(`    ${contentJsx.split('\n').join('\n    ')}`)
  parts.push(`  )`)
  parts.push(`}`)

  // dev 下自接受热更新:阻止 vite 因页面模块无 importer 而整页刷新;
  // 内容替换由客户端 vitepress:pageData 事件驱动(重新 import 新模块)
  parts.push(`if (import.meta.hot) { import.meta.hot.accept() }`)

  return parts.join('\n')
}
